apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-orders
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-orders
  template:
    metadata:
      labels:
        app: api-orders
    spec:
      containers:
      - name: api-orders
        image: api-orders:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        env:
        - name: POSTGRES_USER
          value: orders
        - name: POSTGRES_PASSWORD
          value: apiOrders
        - name: POSTGRES_DB
          value: orders_db
        - name: POSTGRES_HOST
          value: postgres-orders
        - name: RABBITMQ_HOST
          value: rabbitmq
        - name: RABBITMQ_PORT
          value: "5672"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-orders
spec:
  clusterIP: None
  selector:
    app: postgres-orders
  ports:
  - port: 5432

apiVersion: v1
kind: Service
metadata:
  name: api-orders
spec:
  type: NodePort
  selector:
    app: api-orders
  ports:
    - port: 8002
      targetPort: 8002


