version: '3.9'

services:
  db:
    image: postgres:13
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - backend
    ports:
      - "5433:5432"
  api:
    build: .
    command: uvicorn app.main:app --host ${API_HOST} --port ${API_PORT}
    volumes:
      - ./:/app
    ports:
      - "${API_PORT}:${API_PORT}"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_HOST=db
      - POSTGRES_PORT=${POSTGRES_PORT}
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    external: true  # Réseau partagé avec RabbitMQ
