name: CI/CD Pipeline for FastAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: orders
          POSTGRES_PASSWORD: apiOrders
          POSTGRES_DB: orders_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v2
      # Cette étape récupère le code source de la branche actuelle

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
      # Configure Python 3.9 pour l'utilisation dans les étapes suivantes

    - name: Set PYTHONPATH
      run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV
      # Définit la variable PYTHONPATH pour s'assurer que Python trouve les modules

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      # Installe les dépendances requises à partir de requirements.txt

    - name: Run tests
      run: |
        pytest tests/
      # Exécute les tests unitaires et d'intégration

    - name: Build Docker image
      run: |
        docker build -t myapi .
      # Construit une image Docker pour l'application
