name: CI/CD Pipeline for FastAPI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    
    env:
      POSTGRES_USER=orders
      POSTGRES_PASSWORD=apiOrders
      POSTGRES_DB=orders_db
      POSTGRES_HOST=db
      POSTGRES_PORT=5432

      API_HOST=0.0.0.0
      API_PORT=8002

      RABBITMQ_HOST=rabbitmq
      RABBITMQ_PORT=5672


    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set PYTHONPATH
      run: |
        echo "PYTHONPATH=${{ github.workspace }}:${{ github.workspace }}/app" >> $GITHUB_ENV

    - name: Run tests
      run: |
        pytest tests/

    - name: Build Docker image
      run: |
        docker build -t myapi .